=== seadas/seadas/seadas-processing/src/main/resources/gov/nasa/gsfc/seadas/processing/core/ParamInfo-1.0.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="paramInfo">
        <xs:complexType>
            <xs:all>
                <xs:element name="programMetaData" >
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="hasParFile" type="xs:boolean"/>
                            <xs:element name="parFileOptionName" type="xs:string" default="par" minOccurs="0"/>
                            <xs:element name="progressRegex" type="xs:string" minOccurs="0"/>
                            <xs:element name="hasProgramDependency" minOccurs="0">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name = "programName"  type="xs:string" />
                                        <xs:element name = "programParamInfo" type="xs:string" />
                                        <xs:element name="isDefault" type="xs:boolean" minOccurs=" 0"/>
                                    </xs:all>
                                </xs:complexType>
                                    </xs:element>
                        </xs:all>
                    </xs:complexType>
                </xs:element>
                <xs:element name="options">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="option" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="name" type="xs:string"/>
                                        <xs:element name="value" type="xs:string" minOccurs="0">
                                            <xs:alternative test="@type eq 'string'" type="xs:string"/>
                                            <xs:alternative test="@type eq 'int'" type="xs:int"/>
                                            <xs:alternative test="@type eq 'boolean'" type="xs:boolean"/>
                                            <xs:alternative test="@type eq 'float'" type="xs:float"/>
                                            <xs:alternative test="@type eq 'double'" type="xs:double"/>
                                        </xs:element>
                                        <xs:element name="default" type="xs:string" minOccurs="0">
                                            <xs:alternative test="@type eq 'string'" type="xs:string"/>
                                            <xs:alternative test="@type eq 'int'" type="xs:int"/>
                                            <xs:alternative test="@type eq 'boolean'" type="xs:boolean"/>
                                            <xs:alternative test="@type eq 'float'" type="xs:float"/>
                                            <xs:alternative test="@type eq 'double'" type="xs:double"/>
                                        </xs:element>
                                        <xs:element name="source" type="xs:string" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="programName" type="xs:string" minOccurs="0"  maxOccurs="1"/>
                                                    <xs:element name="programParamInfo" type="xs:string" minOccurs="0"  maxOccurs="1"/>
                                                </xs:sequence>
                                                <xs:attribute name="isProgram" type="xs:boolean">

                                                </xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="order" type="xs:string" minOccurs="0"/>
                                        <xs:element name="aliases" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="alias" type="xs:string" maxOccurs="unbounded"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="validValues" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="validValue" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:all>
                                                                <xs:element name="value" type="xs:string">
                                                                    <xs:alternative test="@type eq 'string'"
                                                                                    type="xs:string"/>
                                                                    <xs:alternative test="@type eq 'int'"
                                                                                    type="xs:int"/>
                                                                    <xs:alternative test="@type eq 'boolean'"
                                                                                    type="xs:boolean"/>
                                                                    <xs:alternative test="@type eq 'float'"
                                                                                    type="xs:float"/>
                                                                    <xs:alternative test="@type eq 'double'"
                                                                                    type="xs:double"/>
                                                                </xs:element>
                                                                <xs:element name="description" type="xs:string"/>
                                                            </xs:all>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="description" type="xs:string" minOccurs="0"/>
                                    </xs:all>
                                    <xs:attribute name="type" default="string">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="string"/>
                                                <xs:enumeration value="int"/>
                                                <xs:enumeration value="boolean"/>
                                                <xs:enumeration value="float"/>
                                                <xs:enumeration value="double"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <xs:attribute name="runtimeOption" type="xs:boolean" default="true"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== seadas/seadas/seadas-processing/src/main/resources/gov/nasa/gsfc/seadas/processing/core/l2extract.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<paramInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="http://seadas.gsfc.nasa.gov/software/schemas/ParamInfo-1.0.xsd">
    <programMetaData>
        <hasParFile>false</hasParFile>
        <parFileOptionName>NO_PAR_FILE</parFileOptionName>
        <primaryOptions>
            <primaryOption>infile</primaryOption>
            <primaryOption>outfile</primaryOption>
        </primaryOptions>
    </programMetaData>
    <options>
        <option type="ifile">
            <name>infile</name>
            <value>q</value>
            <default></default>
            <description>input SEAWIFS L1A datafile</description>
            <source>command line</source>
            <aliases>
                <alias>ifile1</alias>
            </aliases>
            <order>1</order>
        </option>
        <option type="int">
            <name>spixl</name>
            <value>1</value>
            <default>1</default>
            <description>start pixel number</description>
            <order>2</order>
        </option>
        <option type="int">
            <name>epixl</name>
            <value>-1</value>
            <default>-1</default>
            <description>end pixel number (-1=the last pixel)</description>
            <order>3</order>
        </option>
        <option type="int">
            <name>sline</name>
            <value>1</value>
            <default>1</default>
            <description>start line number</description>
            <order>4</order>
        </option>
        <option type="int">
            <name>eline</name>
            <value>-1</value>
            <default>-1</default>
            <description>end line number (-1=the last line)</description>
            <order>5</order>
        </option>
        <option type="int">
            <name>pix_sub</name>
            <value>1</value>
            <default>1</default>
            <description>pixel subsampling rate</description>
            <order>6</order>
        </option>
        <option type="int">
            <name>sc_sub</name>
            <value>1</value>
            <default>-1</default>
            <description>scan line subsampling rate</description>
            <order>7</order>
        </option>
        <option type="ofile">
            <name>outfile</name>
            <value></value>
            <default>output</default>
            <description>output L2 file name</description>
            <order>8</order>
        </option>
        <option type="string">
            <name>prod_list</name>
            <value></value>
            <default></default>
            <description>product list (optional)</description>
            <order>9</order>
        </option>
    </options>
</paramInfo>

=== seadas/seadas/seadas-processing/src/main/resources/gov/nasa/gsfc/seadas/processing/core/modis_GEO.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<paramInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="http://seadas.gsfc.nasa.gov/software/schemas/ParamInfo-1.0.xsd">>
    <programMetaData>
        <hasParFile>false</hasParFile>
        <parFileOptionName>--parfile</parFileOptionName>
        <primaryOptions>
            <primaryOption>file</primaryOption>
            <primaryOption>--output</primaryOption>
        </primaryOptions>
    </programMetaData>
    <options>
        <option type="ifile">
            <name>file</name>
            <value></value>
            <default></default>
            <description>Input file</description>
            <source>command line</source>
            <usedAs>argument</usedAs>
            <order>1</order>
        </option>
        <option type="ofile">
            <name>--output</name>
            <value></value>
            <default></default>
            <description>generated GEO file</description>
            <usedAs>option</usedAs>
            <order>2</order>
        </option>
        <option type="string">
            <name>--att1</name>
            <value></value>
            <type>string</type>
            <default>ATT1</default>
            <description>Input attitude file 1 (chronological)</description>
            <source>default</source>
            <usedAs>option</usedAs>
            <order>3</order>
        </option>
        <option type="string">
            <name>--att2</name>
            <value></value>
            <type>string</type>
            <default>ATT2</default>
            <description>Input attitude file 2 (chronological)</description>
            <source>default</source>
            <usedAs>option</usedAs>
            <order>4</order>
        </option>
        <option type="string">
            <name>--eph1</name>
            <value></value>
            <type>string</type>
            <default>EPH1</default>
            <description>Input ephemeris file 1 (chronological)</description>
            <source>default</source>
            <usedAs>option</usedAs>
            <order>5</order>
        </option>
        <option type="string">
            <name>--eph2</name>
            <value></value>
            <type>string</type>
            <default>EPH2</default>
            <description>Input ephemeris file 2 (chronological)</description>
            <source>default</source>
            <usedAs>option</usedAs>
            <order>6</order>
        </option>
        <option type="string">
            <name>--ancdir</name>
            <value></value>
            <default>ANCDIR</default>
            <description>Use a custom directory tree for ancillary files</description>
            <usedAs>option</usedAs>
            <order>7</order>
        </option>
        <option type="string">
            <name>--ancdb</name>
            <value></value>
            <default>ANCDB</default>
            <description>Use a custom file for ancillary database. If full path
                not given, ANCDB is assumed to exist (or will be
                created) under $OCSSWROOT/log/. If $OCSSWROOT/log/
                does not exist, ANCDB is assumed (or will be created)
                under the current working directory
            </description>
            <usedAs>option</usedAs>
            <order>8</order>
        </option>
        <option type="string">
            <name>--threshold</name>
            <value></value>
            <default>THRESHOLD</default>
            <description>% of geo-populated pixels required to pass geocheck validation test</description>
            <usedAs>option</usedAs>
            <order>9</order>
        </option>
        <option type="boolean">
            <name>--refreshDB</name>
            <value></value>
            <default></default>
            <description>Remove existing database records and re-query for ancillary files</description>
            <usedAs>flag</usedAs>
            <order>10</order>
        </option>
        <option type="boolean">
            <name>--disable-download</name>
            <value></value>
            <default></default>
            <description>Disable download of ancillary files not found on hard disk</description>
              <usedAs>flag</usedAs>
            <order>11</order>
        </option>
        <option type="boolean">
            <name>--enable-dem</name>
            <value></value>
            <default></default>
            <description>Enable MODIS terrain elevation correction</description>
            <usedAs>flag</usedAs>
            <order>12</order>
        </option>
        <option type="boolean">
            <name>--verbose</name>
            <value></value>
            <default></default>
            <description>print status messages</description>
            <usedAs>flag</usedAs>
            <order>13</order>
        </option>

        <option type="boolean">
            <name>--log</name>
            <value></value>
            <default></default>
            <description>Save processing log files</description>
            <usedAs>flag</usedAs>
            <order>14</order>
        </option>
    </options>
</paramInfo>

=== seadas/seadas/seadas-processing/src/main/resources/gov/nasa/gsfc/seadas/processing/general/lonlat2pixline.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<paramInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="http://seadas.gsfc.nasa.gov/software/schemas/ParamInfo-1.0.xsd">
    <programMetaData>
        <hasParFile>false</hasParFile>
        <parFileOptionName>NO_PAR_FILE</parFileOptionName>
    </programMetaData>
    <options>
        <option type="ifile">
            <name>infile</name>
            <value></value>
            <default></default>
            <description>is either a L1B, L2, or GEO filename</description>
            <source>command line</source>
            <aliases>
                <alias>ifile1</alias>
            </aliases>
            <order>1</order>
        </option>
        <option type="int">
            <name>SWlon</name>
            <value>1</value>
            <default>1</default>
            <description>start pixel number</description>
            <order>2</order>
        </option>
        <option type="int">
            <name>SWlat</name>
            <value>-1</value>
            <default>-1</default>
            <description>end pixel number (-1=the last pixel)</description>
            <order>3</order>
        </option>
        <option type="int">
            <name>NElon</name>
            <value>1</value>
            <default>1</default>
            <description>start line number</description>
            <order>4</order>
        </option>
        <option type="int">
            <name>NElat</name>
            <value>-1</value>
            <default>-1</default>
            <description>end line number (-1=the last line)</description>
            <order>5</order>
        </option>
      </options>
</paramInfo>

=== seadas/seadas/seadas-processing/src/main/resources/gov/nasa/gsfc/seadas/processing/core/extractor.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<paramInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="http://seadas.gsfc.nasa.gov/software/schemas/ParamInfo-1.0.xsd">
    <programMetaData>
        <hasParFile>false</hasParFile>
        <primaryOptions>
            <primaryOption>ifile</primaryOption>
            <primaryOption>ofile</primaryOption>
        </primaryOptions>
    </programMetaData>
    <options>
        <option type="ifile">
            <name>ifile</name>
            <value></value>
            <default></default>
            <description>input SEAWIFS L1A datafile</description>
            <source>command line</source>
            <aliases>
                <alias>ifile1</alias>
            </aliases>
            <usedAs>argument</usedAs>
            <order>1</order>
        </option>
        <option type="int">
            <name>spixl</name>
            <value>1</value>
            <default>1</default>
            <description>start pixel number</description>
            <usedAs>argument</usedAs>
            <order>2</order>
        </option>
        <option type="int">
            <name>epixl</name>
            <value>-1</value>
            <default>-1</default>
            <description>end pixel number (-1=the last pixel)</description>
            <usedAs>argument</usedAs>
            <order>3</order>
        </option>
        <option type="int">
            <name>sline</name>
            <value>1</value>
            <default>1</default>
            <description>start line number</description>
            <usedAs>argument</usedAs>
            <order>4</order>
        </option>
        <option type="int">
            <name>eline</name>
            <value>-1</value>
            <default>-1</default>
            <description>end line number (-1=the last line)</description>
            <usedAs>argument</usedAs>
            <order>5</order>
        </option>
        <option type="int">
            <name>pix_sub</name>
            <value>1</value>
            <default>1</default>
            <description>start line number</description>
            <usedAs>argument</usedAs>
            <order>6</order>
        </option>
        <option type="int">
            <name>sc_sub</name>
            <value>1</value>
            <default>-1</default>
            <description>end line number (-1=the last line)</description>
            <usedAs>argument</usedAs>
            <order>7</order>
        </option>
        <option type="ofile">
            <name>ofile</name>
            <value></value>
            <default>output</default>
            <description>output L2 file name</description>
            <usedAs>argument</usedAs>
            <order>8</order>
        </option>
    </options>
</paramInfo>
