=== seadas/seadas/seadas-processing/src/main/resources/gov/nasa/gsfc/seadas/processing/core/ParamInfo-1.0.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="paramInfo">
        <xs:complexType>
            <xs:all>
                <xs:element name="programMetaData" >
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="hasParFile" type="xs:boolean"/>
                            <xs:element name="parFileOptionName" type="xs:string" default="par" minOccurs="0"/>
                            <xs:element name="progressRegex" type="xs:string" minOccurs="0"/>
                            <xs:element name="hasProgramDependency" minOccurs="0">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name = "programName"  type="xs:string" />
                                        <xs:element name = "programParamInfo" type="xs:string" />
                                        <xs:element name="isDefault" type="xs:boolean" minOccurs=" 0"/>
                                    </xs:all>
                                </xs:complexType>
                                    </xs:element>
                        </xs:all>
                    </xs:complexType>
                </xs:element>
                <xs:element name="options">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="option" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="name" type="xs:string"/>
                                        <xs:element name="value" type="xs:string" minOccurs="0">
                                            <xs:alternative test="@type eq 'string'" type="xs:string"/>
                                            <xs:alternative test="@type eq 'int'" type="xs:int"/>
                                            <xs:alternative test="@type eq 'boolean'" type="xs:boolean"/>
                                            <xs:alternative test="@type eq 'float'" type="xs:float"/>
                                            <xs:alternative test="@type eq 'double'" type="xs:double"/>
                                        </xs:element>
                                        <xs:element name="default" type="xs:string" minOccurs="0">
                                            <xs:alternative test="@type eq 'string'" type="xs:string"/>
                                            <xs:alternative test="@type eq 'int'" type="xs:int"/>
                                            <xs:alternative test="@type eq 'boolean'" type="xs:boolean"/>
                                            <xs:alternative test="@type eq 'float'" type="xs:float"/>
                                            <xs:alternative test="@type eq 'double'" type="xs:double"/>
                                        </xs:element>
                                        <xs:element name="source" type="xs:string" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="programName" type="xs:string" minOccurs="0"  maxOccurs="1"/>
                                                    <xs:element name="programParamInfo" type="xs:string" minOccurs="0"  maxOccurs="1"/>
                                                </xs:sequence>
                                                <xs:attribute name="isProgram" type="xs:boolean">

                                                </xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="order" type="xs:string" minOccurs="0"/>
                                        <xs:element name="aliases" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="alias" type="xs:string" maxOccurs="unbounded"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="validValues" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="validValue" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:all>
                                                                <xs:element name="value" type="xs:string">
                                                                    <xs:alternative test="@type eq 'string'"
                                                                                    type="xs:string"/>
                                                                    <xs:alternative test="@type eq 'int'"
                                                                                    type="xs:int"/>
                                                                    <xs:alternative test="@type eq 'boolean'"
                                                                                    type="xs:boolean"/>
                                                                    <xs:alternative test="@type eq 'float'"
                                                                                    type="xs:float"/>
                                                                    <xs:alternative test="@type eq 'double'"
                                                                                    type="xs:double"/>
                                                                </xs:element>
                                                                <xs:element name="description" type="xs:string"/>
                                                            </xs:all>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="description" type="xs:string" minOccurs="0"/>
                                    </xs:all>
                                    <xs:attribute name="type" default="string">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="string"/>
                                                <xs:enumeration value="int"/>
                                                <xs:enumeration value="boolean"/>
                                                <xs:enumeration value="float"/>
                                                <xs:enumeration value="double"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <xs:attribute name="runtimeOption" type="xs:boolean" default="true"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== seadas/seadas/seadas-processing/src/main/resources/gov/nasa/gsfc/seadas/processing/core/l1aextract_seawifs.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<paramInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="https://seadas.gsfc.nasa.gov/software/schemas/ParamInfo-1.0.xsd">
    <programMetaData>
        <hasParFile>false</hasParFile>
        <parFileOptionName>NO_PAR_FILE</parFileOptionName>
        <primaryOptions>
            <primaryOption>infile</primaryOption>
            <primaryOption>ofile</primaryOption>
        </primaryOptions>
    </programMetaData>
    <options>
        <option type="ifile">
            <name>infile</name>
            <value></value>
            <default></default>
            <description>input SEAWIFS L1A datafile</description>
            <source>command line</source>
            <aliases>
                <alias>ifile1</alias>
            </aliases>
            <usedAs>argument</usedAs>
            <order>0</order>
        </option>
        <option type="int">
            <name>spixl</name>
            <value></value>
            <default></default>
            <description>start pixel number</description>
            <usedAs>argument</usedAs>
            <order>1</order>
        </option>
        <option type="int">
            <name>epixl</name>
            <value></value>
            <default></default>
            <description>end pixel number</description>
            <usedAs>argument</usedAs>
            <order>2</order>
        </option>
        <option type="int">
            <name>sline</name>
            <value></value>
            <default></default>
            <description>start scan line</description>
            <usedAs>argument</usedAs>
            <order>3</order>
        </option>
        <option type="int">
            <name>eline</name>
            <value></value>
            <default></default>
            <description>end scan line</description>
            <usedAs>argument</usedAs>
            <order>4</order>
        </option>
        <option type="int">
            <name>pix_sub</name>
            <value>1</value>
            <default></default>
            <description>pixel subsampling rate</description>
            <usedAs>argument</usedAs>
            <order>5</order>
        </option>
        <option type="int">
            <name>sc_sub</name>
            <value>1</value>
            <default></default>
            <description>scan line subsampling rate</description>
            <usedAs>argument</usedAs>
            <order>6</order>
        </option>
        <option type="ofile">
            <name>ofile</name>
            <value></value>
            <default></default>
            <description>output file name</description>
            <usedAs>argument</usedAs>
            <order>7</order>
        </option>
    </options>
</paramInfo>

=== seadas/seadas/seadas-processing/src/main/resources/gov/nasa/gsfc/seadas/processing/core/l2bin.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<paramInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="http://seadas.gsfc.nasa.gov/software/schemas/ParamInfo-1.0.xsd">
    <programMetaData>
        <hasParFile>true</hasParFile>
        <parFileOptionName>par</parFileOptionName>
        <!--krow:   810 out of   2160  (-22.50 to   0.00) Tue Jun 26 16:14:55 2012-->
        <progressRegex>krow: +(\d+) out of +(\d+)</progressRegex>
        <primaryOptions>
            <primaryOption>infile</primaryOption>
            <primaryOption>ofile</primaryOption>
        </primaryOptions>
    </programMetaData>
    <options>
        <option type="ifile">
            <name>infile</name>
            <value></value>
            <default></default>
            <description>input L1 file name</description>
            <source>command line</source>
            <aliases>
                <alias>ifile1</alias>
            </aliases>
            <multiFile>true</multiFile>
            <order>1</order>
        </option>
        <option type="ofile">
            <name>ofile</name>
            <value></value>
            <default>output</default>
            <description>output L2 file #1 name, output vicarious L1B for inverse mode</description>
            <alias>ofile1</alias>
            <order>2</order>
        </option>
        <option type="string">
            <name>sday</name>
            <value></value>
            <default></default>
            <description>start datadate (YYYYDDD) [ignored for "regional" prodtype]</description>
            <order>3</order>
        </option>
        <option type="string">
            <name>eday</name>
            <value></value>
            <default></default>
            <description>end datadate (YYYYDDD) [ignored for "regional" prodtype]</description>
            <order>4</order>
        </option>
        <!--<option type="int">-->
            <!--<name>resolve</name>-->
            <!--<value>1</value>-->
            <!--<default>1</default>-->
            <!--<description>bin resolution (H,1,2,4,9,36)</description>-->
            <!--<order>5</order>-->
        <!--</option>-->
        <option type="int">
            <name>resolve</name>
            <value></value>
            <type>int</type>
            <default>9</default>
            <description>bin resolution (H,1,2,4,9,36)
            </description>
            <source>default</source>
            <validValue>
                <value>H</value>
                <description>500m</description>
            </validValue>
            <validValue>
                <value>1</value>
                <description>1km</description>
            </validValue>
            <validValue>
                <value>2</value>
                <description>2km</description>
            </validValue>
            <validValue>
                <value>4</value>
                <description>4km</description>
            </validValue>
            <validValue>
                <value>9</value>
                <description>9km</description>
            </validValue>
            <validValue>
                <value>36</value>
                <description>36km</description>
            </validValue>
            <order>5</order>
        </option>
        <option type="string">
            <name>flaguse</name>
            <value></value>
            <default></default>
            <description>flags masked [see /SENSOR/l2bin_defaults.par]</description>
            <order>6</order>
        </option>
        <option type="string">
            <name>l3bprod</name>
            <value></value>
            <default></default>
            <description>bin products [default=all products]
                Set to "ALL" or "all" for all L2 products in 1st input file.
                Use ':' or ',' or ' ' as delimiters.
                Use ';' or '=' to delineate minimum values.
            </description>
            <order>7</order>
        </option>
        <option type="string">
            <name>prodtype</name>
            <value></value>
            <default>day</default>
            <description>product type (Set to "regional" to bin all scans.) [default=day]</description>
            <order>8</order>
        </option>
        <option type="string">
            <name>pversion</name>
            <value></value>
            <default></default>
            <description>production version [default=Unspecified]</description>
            <order>9</order>
        </option>
        <option type="boolean">
            <name>noext</name>
            <value>true</value>
            <default>true</default>
            <description>set to 1 to suppress generation of external files [default=1, (1 for "regional" prodtype)]
            </description>
            <order>10</order>
        </option>

        <option type="int">
            <name>rowgroup</name>
            <value></value>
            <default></default>
            <description># of bin rows to process at once</description>
            <order>11</order>
        </option>
        <option type="boolean">
            <name>night</name>
            <value></value>
            <default>false</default>
            <description>set to 1 for SST night processing [default=0]</description>
            <order>12</order>
        </option>
        <option type="string">
            <name>qual_prod</name>
            <value></value>
            <default></default>
            <description>quality product field name</description>
            <order>13</order>
        </option>
        <option type="int">
            <name>qual_max</name>
            <value></value>
            <default>2</default>
            <description>maximum acceptable quality [default=2]</description>
            <order>14</order>
        </option>
        <option type="boolean">
            <name>verbose</name>
            <value>true</value>
            <default></default>
            <description>Allow more verbose screen messages [default shoulbe true for GUI]</description>
            <order>15</order>
        </option>
    </options>
</paramInfo>

=== seadas/seadas/seadas-processing/src/main/resources/gov/nasa/gsfc/seadas/processing/core/l2bin_aquarius.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<paramInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="https://seadas.gsfc.nasa.gov/software/schemas/ParamInfo-1.0.xsd">>
    <programMetaData>
        <hasParFile>false</hasParFile>
        <parFileOptionName>--parfile</parFileOptionName>
        <primaryOptions>
            <primaryOption>infile</primaryOption>
            <primaryOption>ofile</primaryOption>
        </primaryOptions>
    </programMetaData>
    <options>
        <option type="ifile">
            <name>infile</name>
            <value></value>
            <default></default>
            <description>Input file</description>
            <source>command line</source>
            <usedAs>option</usedAs>
            <order>0</order>
        </option>
        <option type="ofile">
            <name>ofile</name>
            <value></value>
            <default></default>
            <description>L3B output filename</description>
            <usedAs>option</usedAs>
            <order>1</order>
        </option>
        <option type="string">
            <name>resolve</name>
            <value>1D</value>
            <default>1D</default>
            <description>the bin resolution (typically '1D')</description>
            <validValue>
                <value>9</value>
                <description>9</description>
            </validValue>
            <validValue>
                <value>18</value>
                <description>18</description>
            </validValue>
            <validValue>
                <value>36</value>
                <description>36</description>
            </validValue>
            <validValue>
                <value>46</value>
                <description>46</description>
            </validValue>
            <validValue>
                <value>72</value>
                <description>72</description>
            </validValue>
            <validValue>
                <value>1D</value>
                <description>1D</description>
            </validValue>
            <validValue>
                <value>144</value>
                <description>144</description>
            </validValue>
            <usedAs>option</usedAs>
            <order>2</order>
        </option>
        <option type="string">
            <name>l3bprod</name>
            <value></value>
            <default></default>
            <description>product list</description>
            <usedAs>option</usedAs>
            <order>3</order>
        </option>
        <option type="string">
            <name>suite</name>
            <value>V5.0.0</value>
            <default>V5.0.0</default>
            <description>suite</description>
            <validValue>
                <value>V5.0.0</value>
                <description>V5.0.0</description>
            </validValue>
            <validValue>
                <value>V5.0.0.RAIN</value>
                <description>V5.0.0.RAIN</description>
            </validValue>
            <validValue>
                <value>V5.0.0.smoothed</value>
                <description>V5.0.0.smoothed</description>
            </validValue>
            <validValue>
                <value>V5.0.0.RAIN.smoothed</value>
                <description>V5.0.0.RAIN.smoothed</description>
            </validValue>
            <usedAs>option</usedAs>
            <order>4</order>
        </option>
        <option type="string">
            <name>beam</name>
            <value></value>
            <default></default>
            <description>the radiometer beam (1-3)</description>
            <validValue>
                <value>1</value>
                <description>the radiometer beam 1</description>
            </validValue>
            <validValue>
                <value>2</value>
                <description>the radiometer beam 2</description>
            </validValue>
            <validValue>
                <value>3</value>
                <description>the radiometer beam 3</description>
            </validValue>

            <usedAs>option</usedAs>
            <order>5</order>
        </option>
        <option type="string">
            <name>flaguse</name>
            <value></value>
            <default></default>
            <description>Flags to apply (uses default flags if nothing entered)</description>
            <usedAs>option</usedAs>
            <order>6</order>
        </option>
        <option type="string">
            <name>filter_width</name>
            <value></value>
            <default></default>
            <description>the angular radius in degrees of the cutoff filter</description>
            <usedAs>option</usedAs>
            <order>7</order>
        </option>
        <option type="int">
            <name>fill</name>
            <value></value>
            <default></default>
            <description>{0,1} {0 - no fill of undefined bins, 1 - fill undefined bins}</description>
            <validValue>
                <value>0</value>
                <description>0 - no fill of undefined bins</description>
            </validValue>
            <validValue>
                <value>1</value>
                <description>1 - fill undefined bins</description>
            </validValue>
            <usedAs>option</usedAs>
            <order>8</order>
        </option>
        <option type="string">
            <name>fit</name>
            <value></value>
            <default></default>
            <description>{"C", "L", "B", "Q"}
                "C" - constant fit (1 parameter)
                "L" - linear fit (2 parameters)
                "B" - bilinear fit (3 parameters)
                "Q" - quadratic fit (4 parameters)
            </description>
            <validValue>
                <value>C</value>
                <description>constant fit (1 parameter)</description>
            </validValue>
            <validValue>
                <value>L</value>
                <description>linear fit (2 parameters)</description>
            </validValue>
            <validValue>
                <value>B</value>
                <description>bilinear fit (3 parameters)</description>
            </validValue>
            <validValue>
                <value>Q</value>
                <description>quadratic fit (4 parameters)</description>
            </validValue>
            <usedAs>option</usedAs>
            <order>9</order>
        </option>
        <option type="string">
            <name>pversion</name>
            <value></value>
            <default></default>
            <description>pversion</description>
            <usedAs>option</usedAs>
            <order>10</order>
        </option>
    </options>
</paramInfo>

=== seadas/seadas/seadas-processing/src/main/resources/gov/nasa/gsfc/seadas/processing/core/ocssw_installer.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<paramInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="http://seadas.gsfc.nasa.gov/software/schemas/ParamInfo-1.0.xsd">
    <programMetaData>
        <hasParFile>false</hasParFile>
        <parFileOptionName>none</parFileOptionName>
    </programMetaData>
    <options>
        <option type="boolean">
            <name>--verbose</name>
            <value>false</value>
            <default>false</default>
            <description>print out verbose status</description>
        </option>
        <option type="boolean">
            <name>--src</name>
            <value>true</value>
            <default>true</default>
            <description>install source code</description>
        </option>
        <option type="boolean">
            <name>--aquarius</name>
            <value>false</value>
            <default>false</default>
            <description>install Aquarius files</description>
        </option>
        <option type="boolean">
            <name>--avhrr</name>
            <value>false</value>
            <default>false</default>
            <description>install AVHRR files</description>
        </option>
        <option type="boolean">
            <name>--czcs</name>
            <value>false</value>
            <default>false</default>
            <description>install CZCS files</description>
        </option>
        <option type="boolean">
            <name>--goci</name>
            <value>false</value>
            <default>false</default>
            <description>install GOCI files</description>
        </option>
        <option type="boolean">
            <name>--hico</name>
            <value>false</value>
            <default>false</default>
            <description>install HICO files</description>
        </option>
        <option type="boolean">
            <name>--meris</name>
            <value>false</value>
            <default>false</default>
            <description>install MERIS files</description>
        </option>
        <option type="boolean">
            <name>--aqua</name>
            <value>false</value>
            <default>false</default>
            <description>install AQUA files</description>
        </option>
        <option type="boolean">
            <name>--terra</name>
            <value>false</value>
            <default>false</default>
            <description>install TERRA files</description>
        </option>
        <option type="boolean">
            <name>--mos</name>
            <value>false</value>
            <default>false</default>
            <description>install MOS files</description>
        </option>
        <option type="boolean">
            <name>--ocm1</name>
            <value>false</value>
            <default>false</default>
            <description>install OCM1 files</description>
        </option>
        <option type="boolean">
            <name>--ocm2</name>
            <value>false</value>
            <default>false</default>
            <description>install OCM2 files</description>
        </option>
        <option type="boolean">
            <name>--ocrvc</name>
            <value>false</value>
            <default>false</default>
            <description>install OCRVC files</description>
        </option>
        <option type="boolean">
            <name>--octs</name>
            <value>false</value>
            <default>false</default>
            <description>install OCTS files</description>
        </option>
        <option type="boolean">
            <name>--osmi</name>
            <value>false</value>
            <default>false</default>
            <description>install OSMI files</description>
        </option>
        <option type="boolean">
            <name>--seawifs</name>
            <value>false</value>
            <default>false</default>
            <description>install SeaWIFS files</description>
        </option>
        <option type="boolean">
            <name>--viirsn</name>
            <value>false</value>
            <default>false</default>
            <description>install VIIRSN files</description>
        </option>
        <option type="boolean">
            <name>--direct-broadcast</name>
            <value>false</value>
            <default>false</default>
            <description>install direct broadcast files</description>
        </option>
        <option type="boolean">
            <name>--eval</name>
            <value>false</value>
            <default>false</default>
            <description>install evaluation sensor files</description>
        </option>
    </options>
</paramInfo>
