=== seadas/seadas/seadas-processing/src/main/resources/gov/nasa/gsfc/seadas/processing/core/ParamInfo-1.0.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="paramInfo">
        <xs:complexType>
            <xs:all>
                <xs:element name="programMetaData" >
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="hasParFile" type="xs:boolean"/>
                            <xs:element name="parFileOptionName" type="xs:string" default="par" minOccurs="0"/>
                            <xs:element name="progressRegex" type="xs:string" minOccurs="0"/>
                            <xs:element name="hasProgramDependency" minOccurs="0">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name = "programName"  type="xs:string" />
                                        <xs:element name = "programParamInfo" type="xs:string" />
                                        <xs:element name="isDefault" type="xs:boolean" minOccurs=" 0"/>
                                    </xs:all>
                                </xs:complexType>
                                    </xs:element>
                        </xs:all>
                    </xs:complexType>
                </xs:element>
                <xs:element name="options">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="option" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="name" type="xs:string"/>
                                        <xs:element name="value" type="xs:string" minOccurs="0">
                                            <xs:alternative test="@type eq 'string'" type="xs:string"/>
                                            <xs:alternative test="@type eq 'int'" type="xs:int"/>
                                            <xs:alternative test="@type eq 'boolean'" type="xs:boolean"/>
                                            <xs:alternative test="@type eq 'float'" type="xs:float"/>
                                            <xs:alternative test="@type eq 'double'" type="xs:double"/>
                                        </xs:element>
                                        <xs:element name="default" type="xs:string" minOccurs="0">
                                            <xs:alternative test="@type eq 'string'" type="xs:string"/>
                                            <xs:alternative test="@type eq 'int'" type="xs:int"/>
                                            <xs:alternative test="@type eq 'boolean'" type="xs:boolean"/>
                                            <xs:alternative test="@type eq 'float'" type="xs:float"/>
                                            <xs:alternative test="@type eq 'double'" type="xs:double"/>
                                        </xs:element>
                                        <xs:element name="source" type="xs:string" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="programName" type="xs:string" minOccurs="0"  maxOccurs="1"/>
                                                    <xs:element name="programParamInfo" type="xs:string" minOccurs="0"  maxOccurs="1"/>
                                                </xs:sequence>
                                                <xs:attribute name="isProgram" type="xs:boolean">

                                                </xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="order" type="xs:string" minOccurs="0"/>
                                        <xs:element name="aliases" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="alias" type="xs:string" maxOccurs="unbounded"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="validValues" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="validValue" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:all>
                                                                <xs:element name="value" type="xs:string">
                                                                    <xs:alternative test="@type eq 'string'"
                                                                                    type="xs:string"/>
                                                                    <xs:alternative test="@type eq 'int'"
                                                                                    type="xs:int"/>
                                                                    <xs:alternative test="@type eq 'boolean'"
                                                                                    type="xs:boolean"/>
                                                                    <xs:alternative test="@type eq 'float'"
                                                                                    type="xs:float"/>
                                                                    <xs:alternative test="@type eq 'double'"
                                                                                    type="xs:double"/>
                                                                </xs:element>
                                                                <xs:element name="description" type="xs:string"/>
                                                            </xs:all>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="description" type="xs:string" minOccurs="0"/>
                                    </xs:all>
                                    <xs:attribute name="type" default="string">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="string"/>
                                                <xs:enumeration value="int"/>
                                                <xs:enumeration value="boolean"/>
                                                <xs:enumeration value="float"/>
                                                <xs:enumeration value="double"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <xs:attribute name="runtimeOption" type="xs:boolean" default="true"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== seadas/seadas/seadas-processing/src/main/resources/gov/nasa/gsfc/seadas/processing/general/l1brsgen.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<paramInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="http://seadas.gsfc.nasa.gov/software/schemas/ParamInfo-1.0.xsd">
    <programMetaData>
        <hasParFile>true</hasParFile>
        <parFileOptionName>par</parFileOptionName>
        <hasGeoFile>true</hasGeoFile>
        <primaryOptions>
            <primaryOption>ifile</primaryOption>
            <primaryOption>ofile</primaryOption>
            <primaryOption>geofile</primaryOption>
        </primaryOptions>
    </programMetaData>
    <options>
        <option type="help">
            <name>-help</name>
            <value>false</value>
            <type>bool</type>
            <default>false</default>
            <description>print usage information</description>
            <source>default</source>
            <alias>-h</alias>
            <alias>--help</alias>
        </option>
        <option type="help">
            <name>-version</name>
            <value>false</value>
            <type>bool</type>
            <default>false</default>
            <description>print the version
                information
            </description>
            <source>default</source>
            <alias>--version</alias>
        </option>
        <option type="help">
            <name>-dump_options</name>
            <value>false</value>
            <type>bool</type>
            <default>false</default>
            <description>print
                information about each option
            </description>
            <source>default</source>
            <alias>--dump_options</alias>
        </option>
        <option type="help">
            <name>-dump_options_paramfile</name>
            <value/>
            <type>string</type>
            <description>print
                information about each option to paramfile
            </description>
            <source>default</source>
            <alias>--dump_options_paramfile</alias>
        </option>
        <option type="help">
            <name>-dump_options_xmlfile</name>
            <value>l1brsgen.xml</value>
            <type>string</type>
            <description>print
                information about each option to XML file
            </description>
            <source>command line</source>
            <alias>--dump_options_xmlfile</alias>
        </option>
        <option type="string">
            <name>pversion</name>
            <value>Unspecified</value>
            <type>string</type>
            <default>Unspecified</default>
            <description>processing version string</description>
            <source>default</source>
        </option>
        <option type="string">
            <name>suite</name>
            <value>OC</value>
            <type>string</type>
            <default>OC</default>
            <description>product suite string for loading
                suite-specific defaults
            </description>
            <source>/Users/Shared/ocssw/run/data/modisa/msl12_defaults.par</source>
        </option>

        <option type="ifile">
            <name>ifile</name>
            <value>/Users/Shared/ocssw/test/l2gen/A2002365234500.L1B_LAC</value>
            <type>string</type>
            <description>input L1 file name</description>
            <source>command line</source>
            <alias>ifile1</alias>
        </option>
        <option type="ifile">
            <name>geofile</name>
            <value/>
            <type>string</type>
            <description>input L1 geolocation file name (MODIS only)</description>
            <source>default</source>
        </option>
        <option type="ofile">
            <name>ofile</name>
            <value>output</value>
            <type>string</type>
            <default>output</default>
            <description>output L2 file #1 name, output vicarious L1B
                for inverse mode
                ofile[#] = additional output L2 file name
            </description>
            <source>default</source>
            <alias>ofile1</alias>
        </option>

        <option type="int">
            <name>spixl</name>
            <value>1</value>
            <type>int</type>
            <default>1</default>
            <description>start pixel number</description>
            <source>/Users/Shared/ocssw/run/data/modisa/l1img_defaults.par</source>
        </option>
        <option type="int">
            <name>epixl</name>
            <value> </value>
            <type>int</type>
            <default>-1</default>
            <description>end pixel number (-1=the last pixel)</description>
            <source>/Users/Shared/ocssw/run/data/modisa/l1img_defaults.par</source>
        </option>
        <option type="int">
            <name>sline</name>
            <value></value>
            <type>int</type>
            <default>1</default>
            <description>start line number</description>
            <source>/Users/Shared/ocssw/run/data/modisa/l1img_defaults.par</source>
        </option>
        <option type="int">
            <name>eline</name>
            <value></value>
            <type>int</type>
            <default>-1</default>
            <description>end line number (-1=the last line)</description>
            <source>/Users/Shared/ocssw/run/data/modisa/l1img_defaults.par</source>
        </option>
               <option type="int">
            <name>subsamp</name>
            <value>1</value>
            <type>int</type>
            <default>1</default>
            <description>sub-sampling interval</description>
            <source></source>
        </option>
               <option type="int">
            <name>rgb</name>
            <value>[1,1,1]</value>
            <type>int</type>
            <default>[1,1,1]</default>
            <description>bands to use for red, green and blue</description>
        </option>
               <option type="boolean">
            <name>atmocor</name>
            <value>true</value>
            <type>boolean</type>
            <default>true</default>
            <description>toggle atmospheric correction</description>
        </option>
        <option type="float">
            <name>datamin</name>
            <value>0.01</value>
            <type>float</type>
            <default>0.01</default>
            <description>minimum value for data scaling
                (default: see product_table)
            </description>
            <source>default</source>
            <!--<validValue>-->
                <!--<value>(default</value>-->
                <!--<description>see product_table)</description>-->
            <!--</validValue>-->
        </option>
        <option type="float">
            <name>datamax</name>
            <value>0.9</value>
            <type>float</type>
            <default>0.9</default>
            <description>maximum value for data scaling
                (default: see product_table)
            </description>
            <source>default</source>
            <!--<validValue>-->
                <!--<value>(default</value>-->
                <!--<description>see product_table)</description>-->
            <!--</validValue>-->
        </option>
        <option type="int">
            <name>stype</name>
            <value>0</value>
            <type>int</type>
            <default>0</default>
            <description>scaling type: 0: log; 1: linear
                (default: see product_table)
            </description>
            <source>default</source>
            <validValue>
                <value>0</value>
                <description>log</description>
            </validValue>
            <validValue>
                <value>1</value>
                <description>linear</description>
            </validValue>
        </option>
        <option type="int">
            <name>outmode</name>
            <value>0</value>
            <type>int</type>
            <default>0</default>
            <description>defines output file format
                0: 8bit HDF
                1: 24bit HDF
                2: PPM
                3: flat binary
                4: PNG
            </description>
            <source>default</source>
            <validValue>
                <value>0</value>
                <description>8 bit HDF browse file</description>
            </validValue>
            <validValue>
                <value>1</value>
                <description>24 bit HDF browse file</description>
            </validValue>
            <validValue>
                <value>2</value>
                <description>PPM color or PGM grayscale image file</description>
            </validValue>
            <validValue>
                <value>3</value>
                <description>flat binary</description>
            </validValue>
            <validValue>
                <value>4</value>
                <description>PNG</description>
            </validValue>
        </option>

    </options>
</paramInfo>

=== seadas/seadas/seadas-processing/src/main/resources/gov/nasa/gsfc/seadas/processing/core/l1aextract_modis.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<paramInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="http://seadas.gsfc.nasa.gov/software/schemas/ParamInfo-1.0.xsd">
    <programMetaData>
        <hasParFile>false</hasParFile>
        <parFileOptionName>NO_PAR_FILE</parFileOptionName>
        <primaryOptions>
            <primaryOption>ifile</primaryOption>
            <primaryOption>ofile</primaryOption>
        </primaryOptions>
    </programMetaData>
    <options>
        <option type="ifile">
            <name>ifile</name>
            <value>q</value>
            <default></default>
            <description>input MODIS L1A datafile</description>
            <source>command line</source>
            <aliases>
                <alias>ifile1</alias>
            </aliases>
            <usedAs>argument</usedAs>
            <order>1</order>
        </option>
        <option type="int">
            <name>spixl</name>
            <value>1</value>
            <default>1</default>
            <description>start pixel number</description>
            <order>2</order>
            <source>lonlat2pixline</source>
            <usedAs>argument</usedAs>
        </option>
        <option type="int">
            <name>epixl</name>
            <value>-1</value>
            <default>-1</default>
            <description>end pixel number (-1=the last pixel)</description>
            <order>3</order>
            <source>lonlat2pixline</source>
            <usedAs>argument</usedAs>
        </option>
        <option type="int">
            <name>sline</name>
            <value>1</value>
            <default>1</default>
            <description>start line number</description>
            <order>4</order>
            <source>lonlat2pixline</source>
            <usedAs>argument</usedAs>
        </option>
        <option type="int">
            <name>eline</name>
            <value>-1</value>
            <default>-1</default>
            <description>end line number (-1=the last line)</description>
            <order>5</order>
            <source>lonlat2pixline</source>
            <usedAs>argument</usedAs>
        </option>
        <option type="ofile">
            <name>ofile</name>
            <value></value>
            <default>output</default>
            <description>output L2 file name</description>
            <usedAs>argument</usedAs>
            <order>6</order>
        </option>
    </options>
</paramInfo>

=== seadas/seadas/seadas-processing/src/main/resources/gov/nasa/gsfc/seadas/processing/core/update_luts.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<paramInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="https://seadas.gsfc.nasa.gov/software/schemas/ParamInfo-1.0.xsd">
    <programMetaData>
        <hasParFile>false</hasParFile>
        <parFileOptionName>none</parFileOptionName>
        <progressRegex>Installing .+(\d+) of (\d+)</progressRegex>
    </programMetaData>
    <options>
        <option type="boolean">
            <name>aquarius</name>
            <value>true</value>
            <default>true</default>
            <usedAs>flag</usedAs>
            <description>install Aquarius files</description>
            <order>2</order>
        </option>
        <option type="boolean">
            <name>aqua</name>
            <value>true</value>
            <default>true</default>
            <usedAs>flag</usedAs>
            <description>install MODIS Aqua files</description>
            <order>8</order>
        </option>
        <option type="boolean">
            <name>terra</name>
            <value>true</value>
            <default>true</default>
            <usedAs>flag</usedAs>
            <description>install MODIS Terra files</description>
            <order>9</order>
        </option>
        <option type="boolean">
            <name>seawifs</name>
            <value>true</value>
            <default>true</default>
            <usedAs>flag</usedAs>
            <description>install SeaWIFS files</description>
            <order>18</order>
        </option>
        <option type="boolean">
            <name>viirsn</name>
            <value>true</value>
            <default>true</default>
            <usedAs>flag</usedAs>
            <description>install VIIRS SNPP files</description>
            <order>19</order>
        </option>
        <option type="boolean">
            <name>viirsj1</name>
            <value>true</value>
            <default>true</default>
            <usedAs>flag</usedAs>
            <description>install VIIRS JPSS1 files</description>
            <order>20</order>
        </option>
        <!--<option type="button">-->
            <!--<name>update luts</name>-->
            <!--<value></value>-->
            <!--<default></default>-->
            <!--<description>update luts for a given mission. MISSION is either seawifs, aqua, terra, or aquarius-->
            <!--</description>-->
            <!--<usedAs>button</usedAs>-->
            <!--<order>15</order>-->
        <!--</option>-->
    </options>
</paramInfo>

=== seadas/seadas/seadas-processing/src/main/resources/gov/nasa/gsfc/seadas/processing/core/modis_L1B.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<paramInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="https://seadas.gsfc.nasa.gov/software/schemas/ParamInfo-1.0.xsd">>
    <programMetaData>
        <hasParFile>false</hasParFile>
        <parFileOptionName>parfile</parFileOptionName>
        <hasGeoFile>true</hasGeoFile>
        <primaryOptions>
            <primaryOption>ifile</primaryOption>
            <primaryOption>geofile</primaryOption>
        </primaryOptions>
        <progressRegex>scan: (\d+) out of (\d+)</progressRegex>
    </programMetaData>
    <options>
        <option type="ifile">
            <name>ifile</name>
            <value></value>
            <default></default>
            <description>Input L1A file</description>
            <source>command line</source>
            <usedAs>argument</usedAs>
            <order>0</order>
        </option>
        <option type="ifile">
            <name>geofile</name>
            <value></value>
            <default></default>
            <description>geo file</description>
            <source>command line</source>
            <usedAs>argument</usedAs>
            <order>1</order>
        </option>
        <option type="ofile">
            <name>--okm</name>
            <value></value>
            <default></default>
            <description>Output MODIS L1B 1KM HDF filename</description>
            <usedAs>option</usedAs>
            <order>2</order>
        </option>
        <option type="ofile">
            <name>--hkm</name>
            <value></value>
            <default></default>
            <description>Output MODIS L1B HKM HDF filename</description>
            <usedAs>option</usedAs>
            <order>3</order>
        </option>
        <option type="ofile">
            <name>--qkm</name>
            <value></value>
            <default></default>
            <description>Output MODIS L1B QKM HDF filename</description>
            <usedAs>option</usedAs>
            <order>4</order>
        </option>
        <option type="ofile">
            <name>--obc</name>
            <value></value>
            <default></default>
            <description>Output MODIS L1B OBC HDF filename</description>
            <usedAs>option</usedAs>
            <order>5</order>
        </option>
        <option type="string">
            <name>--lutver</name>
            <value></value>
            <default></default>
            <description>L1B LUT version number</description>
            <usedAs>option</usedAs>
            <order>6</order>
        </option>
        <option type="dir">
            <name>--lutdir</name>
            <value></value>
            <default></default>
            <description>Path of directory containing LUT files</description>
            <usedAs>option</usedAs>
            <order>7</order>
        </option>
        <option type="boolean">
            <name>--del-okm</name>
            <value></value>
            <default></default>
            <description>Path of directory containing LUT files</description>
            <usedAs>flag</usedAs>
            <order>8</order>
        </option>
        <option type="boolean">
            <name>--del-hkm</name>
            <value></value>
            <default></default>
            <description>Path of directory containing LUT files</description>
            <usedAs>flag</usedAs>
            <order>9</order>
        </option>
        <option type="boolean">
            <name>--del-qkm</name>
            <value></value>
            <default></default>
            <description>Path of directory containing LUT files</description>
            <usedAs>flag</usedAs>
            <order>10</order>
        </option>
        <option type="boolean">
            <name>--keep-obc</name>
            <value></value>
            <default></default>
            <description>Path of directory containing LUT files</description>
            <usedAs>flag</usedAs>
            <order>11</order>
        </option>
        <option type="boolean">
            <name>--log</name>
            <value></value>
            <default></default>
            <description>Path of directory containing LUT files</description>
            <usedAs>flag</usedAs>
            <order>12</order>
        </option>
        <option type="boolean">
            <name>--verbose</name>
            <value>true</value>
            <default></default>
            <description>Path of directory containing LUT files</description>
            <usedAs>flag</usedAs>
            <order>13</order>
        </option>
        <option type="button">
            <name>update luts</name>
            <value></value>
            <default></default>
            <description>update luts for a given mission. MISSION is either seawifs, aqua, terra, or aquarius
            </description>
            <usedAs>button</usedAs>
            <order>14</order>
        </option>
    </options>
</paramInfo>

=== seadas/seadas/seadas-processing/src/main/resources/gov/nasa/gsfc/seadas/processing/core/multilevel_processor.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<paramInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="https://seadas.gsfc.nasa.gov/software/schemas/ParamInfo-1.0.xsd">
    <programMetaData>
        <hasParFile>true</hasParFile>
        <parFileOptionName>par</parFileOptionName>
        <primaryOptions>
            <primaryOption>ifile</primaryOption>
        </primaryOptions>
    </programMetaData>
    <options>
        <option type="ifile">
            <name>ifile</name>
            <value/>
            <default></default>
            <description>input datafiles or list of files</description>
        </option>
        <option type="ofile">
            <name>odir</name>
            <value/>
            <default></default>
            <description>output directory</description>
        </option>
        <option type="boolean">
            <name>verbose</name>
            <value>false</value>
            <default>false</default>
            <description>print out verbose status</description>
        </option>
        <option type="boolean">
            <name>overwrite</name>
            <value>false</value>
            <default>false</default>
            <description>overwrite existing intermediate and output files</description>
        </option>
        <option type="boolean">
            <name>use_existing</name>
            <value>false</value>
            <default>false</default>
            <description>do not re-create intermediate files if they already exist</description>
        </option>
        <option type="boolean">
            <name>ocproc_getanc</name>
            <value>false</value>
            <default>false</default>
            <description>Get the ancillary data for l2gen processing</description>
        </option>
    </options>
</paramInfo>
